// Alunos: Adryan Costa Silva, Hassan Ali El Gazouini, Hussein ALi El Gazouini, Murilo Zimerman Fortaleza
//
// Interface Logger
//
// Compilar com:
//
//     tao_idl -Gstl Logger.idl
//
// para gerar stub e skeleton.

exception SemEventosComNivel {};

interface Logger {

    // atributos
    enum severidade {DEBUG, WARNING, ERROR, CRITICAL};

    // métodos
    oneway void log(in severidade nivel, in string endereco, in unsigned short pid, in unsigned long hora, in string msg);

    string locate(in severidade s) raises (SemEventosComNivel);
};
