// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.4
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1621

#include "LoggerI.h"
#include <iostream>

using namespace std;

// Implementation skeleton constructor
Logger_i::Logger_i ()
{
}

// Implementation skeleton destructor
Logger_i::~Logger_i ()
{
}

void Logger_i::log (
  ::Logger::severidade nivel,
  const std::string endereco,
  ::CORBA::UShort pid,
  ::CORBA::ULong hora,
  const std::string msg)
{
  // Add your implementation here
  cout << nivel << " : " 
       << endereco << " : " 
       << pid << " : " 
       << hora << " : " 
       << msg << endl;

  if (nivel == Logger::DEBUG){
    ultimo_debug = endereco;
  } else if (nivel == Logger::WARNING){
    ultimo_warning = endereco;
  } else if (nivel == Logger::ERROR){
    ultimo_error = endereco;
  } else {
    ultimo_critical = endereco;
  }
}

std::string Logger_i::locate (
  ::Logger::severidade s)
{
  // Add your implementation here
  if (s == Logger::DEBUG){
    if (ultimo_debug.empty()){
      throw SemEventosComNivel();
    }

    return ultimo_debug;
  } 
  else if (s == Logger::WARNING){
    if (ultimo_warning.empty()){
      throw SemEventosComNivel();
    }

    return ultimo_warning;
  } 
  else if (s == Logger::ERROR){
    if (ultimo_error.empty()){
      throw SemEventosComNivel();
    }

    return ultimo_error;
  } 
  else {
    if (ultimo_critical.empty()){
      throw SemEventosComNivel();
    }

    return ultimo_critical;
  }
}

